sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  - WP_PROJECT_TYPE=plugin WP_VERSION=latest WP_MULTISITE=0 WP_TEST_URL=http://localhost:12000 WP_TEST_USER=test WP_TEST_USER_PASS=test

matrix:
  include:
    - php: "5.6"
      env: WP_VERSION=master WP_ALLOW_MULTISITE=1
    - php: "7"
      env: WP_VERSION=master
    - php: "7"
      env: WP_VERSION=master WP_ALLOW_MULTISITE=1      
    - php: "7.1"
      env: WP_VERSION=master
    - php: "7.2"
      env: WP_VERSION=master

before_script:
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION

script:
  - cd wp-tests/spec && bundle exec rspec test.rb

branches:
  only:
    - master
    - /^release\/.*$/


notifications:
    slack: kbsupport:4jojNlDtoZ6qLQbeSjJ5ivFX