sudo: false
language: php

notifications:
  on_success: never
  on_failure: change

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.9 WP_MULTISITE=0
- WP_VERSION=4.8.3 WP_MULTISITE=0
- WP_VERSION=4.7.7 WP_MULTISITE=0
- WP_VERSION=4.6.8 WP_MULTISITE=0
- WP_VERSION=4.5.11 WP_MULTISITE=0
- WP_VERSION=4.4.2 WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.1
      env: WP_VERSION=4.7 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.7 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.6 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.5 WP_MULTISITE=0
      dist: precise
    - php: 5.3
      env: WP_VERSION=4.4 WP_MULTISITE=0
      dist: precise

before_script:
  - git clone https://github.com/Seravo/wordpress-test-template wp-tests
  - bash wp-tests/bin/install-wp-tests.sh test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - cd wp-tests/spec && bundle exec rspec test.rb

branches:
  only:
    - master
    - /^release\/.*$/

notifications:
    slack: kbsupport:4jojNlDtoZ6qLQbeSjJ5ivFX
